services:
  db:
    container_name: alocarec-db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    #expose:Comentado, para testar se o banco de dados está funcionando externamente
    #  - '5432'
    networks:
      - alocarec-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: alocarec-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}      
    networks:
      - alocarec-network

  migrate:
    container_name: alocarec-migrate
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      app:
        condition: service_started
    command: /bin/sh -c "npx prisma migrate dev --name init && npm run prisma:seed"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - alocarec-network
    restart: "no"

networks:
  alocarec-network:
    name: alocarec-network

volumes:
  pgdata:
    name: alocarec-pgdata
 